# 开发环境配置

app:
  env: dev

# 日志配置
logging:
  level:
    root: INFO
    com.adminplus: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE